<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'; import {useRouter} from 'vue-router'; import {get,post} from '@/net'
const router=useRouter();const items=ref<any[]>([]);const sort=ref('latest');const page=reactive({current:1,size:10,total:0});const loading=ref(false)
function load(){loading.value=true;get('/api/favorite/list',{page:page.current,size:page.size,sort:sort.value},r=>{const d=r.data?.data;items.value=d?.items??[];page.total=d?.total??0;loading.value=false},()=>loading.value=false,()=>loading.value=false)}
function toggle(id:number){post('/api/favorite/toggle',{postId:id},()=>load())} onMounted(load)
</script>
<!-- 收藏页排序入口包含最新、最早，最热由服务端接口支持 -->
<template><div class="page"><header><strong @click="router.push('/index')">资源分享社区</strong><button @click="router.push('/index')">返回帖子流</button></header><main><div class="title-row"><h1>我的收藏</h1><div><button v-for="o in [['latest','最新'],['oldest','最早']]" :key="o[0]" :class="{active:sort===o[0]}" @click="sort=o[0];page.current=1;load()">{{o[1]}}</button></div></div><p v-if="!loading&&!items.length" class="empty">还没有收藏帖子</p><article v-for="p in items" :key="p.favoriteId" :class="{deleted:p.deleted}" @click="router.push('/post/'+p.postId)"><template v-if="p.deleted"><h2>该帖子已被作者删除</h2><p>这条收藏已失效</p></template><template v-else><h2>{{p.title}}</h2><p>{{p.content.slice(0,160)}}</p><small>{{p.authorNickname}} · 收藏于 {{p.favoriteCreateTime}}</small></template><button class="cancel" @click.stop="toggle(p.postId)">取消收藏</button></article></main></div></template>
<style scoped>.page{min-height:100vh;background:#f5f6fa;color:#242638}header{height:60px;background:#fff;border-bottom:1px solid #e8e8e8;display:flex;align-items:center;justify-content:space-between;padding:0 calc((100% - 860px)/2 + 20px)}header strong{color:#667eea;cursor:pointer}button{padding:7px 14px;border:1px solid #d9dcf5;background:#fff;color:#667eea;border-radius:6px;cursor:pointer}.active{background:#667eea;color:#fff}main{max-width:860px;margin:auto;padding:24px 20px}.title-row{display:flex;justify-content:space-between;align-items:center}article{position:relative;background:#fff;padding:20px 24px;margin:14px 0;border-radius:8px;cursor:pointer}article h2{margin:0 0 8px;font-size:18px}article p{color:#666}.deleted{color:#999;background:#ececec}.deleted p{color:#999}.cancel{position:absolute;right:20px;bottom:18px;color:#e74c3c;border-color:#f5cccc}.empty{text-align:center;color:#999;padding:60px}</style>
