<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { useRouter } from 'vue-router'
import { aiChat, get } from '@/net'
const router=useRouter(); const posts=ref<any[]>([]); const sort=ref('latest'); const loading=ref(false); const page=reactive({current:1,size:10,total:0}); const summaries=ref<Record<number,string>>({}); const summarizingId=ref<number|null>(null)
function load(){loading.value=true;get('/api/post/mine',{page:page.current,size:page.size,sort:sort.value},r=>{const d=r.data?.data;posts.value=d?.items??[];page.total=d?.total??0;loading.value=false},()=>loading.value=false,()=>loading.value=false)}
function remove(id:number){if(!confirm('确定删除这篇帖子吗？'))return; import('@/net').then(({post})=>post(`/api/post/${id}`,null,()=>load()))}
function summarize(id:number){if(summarizingId.value!==null)return;summarizingId.value=id;aiChat({message:'概括这篇帖子的正文',targetPostId:id},r=>{const d=r.data?.data;summaries.value[id]=d?.summary||d?.reply||'暂时没有生成概括';summarizingId.value=null},()=>summarizingId.value=null,()=>summarizingId.value=null)}
onMounted(load)
</script>
<template><div class="page"><header><strong @click="router.push('/index')">资源分享社区</strong><button @click="router.push('/index')">返回帖子流</button></header><main><div class="title-row"><h1>我的发布</h1><div><button v-for="o in [['latest','最新'],['hot','最热'],['oldest','最早']]" :key="o[0]" :class="{active:sort===o[0]}" @click="sort=o[0];page.current=1;load()">{{o[1]}}</button></div></div><p v-if="!loading&&!posts.length" class="empty">还没有发布内容</p><article v-for="p in posts" :key="p.id" @click="router.push('/post/'+p.id)"><h2>{{p.title}}</h2><p>{{p.content.slice(0,160)}}</p><p v-if="summaries[p.id]" class="summary"><strong>正文概括：</strong>{{summaries[p.id]}}</p><small>{{p.createTime}} · 👍 {{p.likeCount}} · 💬 {{p.commentCount}}</small><span class="ops"><button @click.stop="router.push('/post/'+p.id+'/edit')">编辑</button><button @click.stop="summarize(p.id)" :disabled="summarizingId!==null">{{summarizingId===p.id?'概括中...':'概括正文'}}</button><button class="danger" @click.stop="remove(p.id)">删除</button></span></article></main></div></template>
<style scoped> .page{min-height:100vh;background:#f5f6fa;color:#242638}header{height:60px;background:#fff;border-bottom:1px solid #e8e8e8;display:flex;align-items:center;justify-content:space-between;padding:0 calc((100% - 860px)/2 + 20px)}header strong{color:#667eea;cursor:pointer}button{padding:7px 14px;border:1px solid #d9dcf5;background:#fff;color:#667eea;border-radius:6px;cursor:pointer}.active{background:#667eea;color:#fff}main{max-width:860px;margin:auto;padding:24px 20px}.title-row{display:flex;justify-content:space-between;align-items:center}h1{font-size:24px}article{position:relative;background:#fff;padding:20px 24px;margin:14px 0;border-radius:8px;cursor:pointer}article h2{margin:0 0 8px;font-size:18px}article p{color:#666;line-height:1.6}small{color:#999}.ops{position:absolute;right:20px;bottom:18px;display:flex;gap:8px}.danger{color:#e74c3c;border-color:#f5cccc}.empty{text-align:center;color:#999;padding:60px}</style>
